- id: '3'
  alias: Evening lights
  trigger:
  - platform: sun
    event: sunset
    offset: 00:15:00
  - platform: sun
    event: sunrise
    offset: 01:00:00
  action:
    service_template: "{% if trigger.event == 'sunset' %}\n  switch.turn_on\n{% else\
      \ %}\n  switch.turn_off\n{% endif %}\n"
    entity_id:
    - switch.downstair_lights
    - switch.upstair_lights
- id: '4'
  alias: Startup notification
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.system
    data_template:
      message: 'Home Assistant has started (IP: {{ states.sensor.ip_address.state
        }})'
      title: System Notification
- id: '5'
  alias: Notify for new devices
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
  - service: notify.system
    data_template:
      message: 'New device: {{trigger.event.data.host_name}} {{trigger.event.data.entity_id}}

        '
      title: System Notification
- id: '6'
  alias: Process monitoring
  trigger:
    platform: state
    entity_id:
    - sensor.process_mosquitto
  action:
    service: notify.system
    data_template:
      message: '{{ trigger.entity_id.split(''.'')[1] }} is {{ trigger.to_state.state.lower()
        }}

        '
      title: System Notification
- id: '7'
  alias: Engine pre-heater
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.engine_heater.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: input_boolean.engine_heater
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.engine_heater
  - service: switch.turn_on
    entity_id: switch.engine_heater
  - service: switch.turn_on
    entity_id: switch.engine
  - service_template: "{% if is_state('input_select.engine_heater', 'Pierre') %}\n\
      \  notify.ios_pierres_iphone\n{% elif is_state('input_select.engine_heater',\
      \ 'Tove') %}\n  notify.ios_toves_iphone\n{% else %}\n  notify.all_people\n{%\
      \ endif %}\n"
    data:
      title: Engine Heater
      message: Turned ON engine heater!
- id: '8'
  alias: Engine pre-heater auto-off
  trigger:
  - platform: template
    value_template: '{% set start = states.input_datetime.engine_heater.attributes.timestamp
      | int %} {% set delay = states.input_number.engine_heater.state | int %} {{
      states(''sensor.time'') == ((start + delay * 60) | timestamp_custom(''%H:%M'',
      False)) }}

      '
  action:
  - service: switch.turn_off
    entity_id: switch.engine_heater
- id: '1551426106718'
  alias: City Gross
  trigger:
  - entity_id: device_tracker.pierres_iphone
    event: enter
    platform: zone
    zone: zone.city_gross_mantorp
  condition: []
  action:
  - data:
      data:
        attachment:
          content-type: png
          hide-thumbnail: 'false'
          url: https://staahl.in/local/license.png
      message: City gross
    service: notify.ios_pierres_iphone
  - data:
      data:
        attachment:
          content-type: png
          hide-thumbnail: 'false'
          url: https://staahl.in/local/license.png
      message: City gross
    service: notify.ios_pierres_iphone
