homeassistant:
  name: !secret hass_name
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: !secret hass_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  whitelist_external_dirs:
    - /hass/

  packages: !include_dir_named packages

automation: !include automations.yaml

calendar:
  - platform: caldav
    username: !secret icloud_username
    password: !secret icloud_password
    url: !secret icloud_calendar
    calendars:
      - Familj

logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
    domains:
      - sun

logger:
  default: warn
map:
ios:
config:
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-food-planning.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
    - /local/custom_ui/state-card-food-planning_es5.html

conversation:
history:
recorder:
  purge_interval: 3
  purge_keep_days: 2
sun:
http:
  server_port: 8123
  ip_ban_enabled: true
  login_attempts_threshold: 15
  base_url: !secret hass_base_url
  ssl_certificate: !secret hass_ssl_certificate
  ssl_key: !secret hass_ssl_key

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
homekit:
alexa:
zwave:
    usb_path: /dev/ttyACM0
    device_config: !include zwave_device_config.yaml
    config_path: /home/homeassistant/.homeassistant/config

device_tracker:
  - platform: nmap_tracker
    hosts: !secret nmap_hosts
    home_interval: 10
    exclude:
      - !secret pierre_iphone_address
      - !secret tove_iphone_address

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

notify:
  - name: all_people
    platform: group
    services:
      - service: ios_pierres_iphone
      - service: ios_toves_iphone
  - name: system
    platform: group
    services:
      - service: ios_pierres_iphone

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - humidity

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac

apple_tv:
  - host: !secret atv_ip
    login_id: !secret atv_login_id
    credentials: !secret atv_credentials

tts:
  - platform: google

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: !secret mqtt_prefix

emulated_hue:
  type: google_home
  listen_port: 80
  host_ip: !secret hass_ip
  expose_by_default: true
  exposed_domains:
    - switch
    - media_player
    - script

