title: Home Sweet Home

resources:
  - url: /local/tracker-card.js?v=1.0.0
    type: js
  - url: /local/mini-media-player-bundle.js?v=1.0.2
    type: module
  - url: /local/button-card.js?v=0.0.5a
    type: module
  - url: /local/custom-lovelace/swipe-card/swipe-card.js?v=2.0.0
    type: module
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.3.4
    type: js
  - url: https://unpkg.com/moment@2.22.2/moment.js?v=0.0.1
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: js
  - url: /local/useful-markdown-card.js?v=9377d8
    type: js
  - url: /local/card-tools.js?v=deb8e3
    type: js

views:
  - title: Home
    icon: mdi:home
    background: center / cover no-repeat url("/local/background.jpg") fixed
    badges:
      - sensor.living_room
      - sensor.bedroom
      - sensor.outside
      - sensor.garage_temperature
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
            - type: custom:button-card
              color: var(--state-icon-active-color)
              color_off: var(--state-icon-color)
              entity: switch.downstair_lights
              icon: mdi:arrow-down-bold
              size: 40px
            - type: custom:button-card
              color: var(--state-icon-active-color)
              color_off: var(--state-icon-color)
              entity: switch.upstair_lights
              icon: mdi:arrow-up-bold
              size: 40px
            - type: custom:button-card
              color: var(--state-icon-active-color)
              color_off: var(--state-icon-color)
              entity: switch.sonos_player
              icon: mdi:music-note
              size: 40px
          - type: horizontal-stack
            cards:
            - type: custom:button-card
              color: var(--state-icon-active-color)
              color_off: var(--state-icon-color)
              entity: script.tv_scene
              icon: mdi:television-classic
              size: 40px
            - type: custom:button-card
              color: var(--state-icon-active-color)
              color_off: var(--state-icon-color)
              entity: script.cinema_scene
              icon: mdi:projector
              size: 40px
            - type: custom:button-card
              color: var(--state-icon-active-color)
              color_off: var(--state-icon-color)
              entity: script.off_scene
              icon: mdi:weather-night
              size: 40px
          - type: glance
            entities:
              - entity: media_player.kok
                name: Sonos
              - entity: media_player.receiver
                name: Receiver
              - entity: media_player.tv
                name: TV
              - entity: switch.projector
                name: Projector
              - entity: cover.garage_door
                name: Garage
      - type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.kok
            name: Sonos
            power_color: true
            hide_volume: false
            group: true
          - type: custom:mini-media-player
            entity: media_player.apple_tv
            name: Apple TV
            power_color: true
            hide_volume: false
            show_progress: true
            group: true
          - type: custom:mini-media-player
            entity: media_player.receiver
            name: Receiver
            power_color: true
            hide_volume: false
            show_progress: true
            group: true
      - type: entities
        title: Engine Heater
        show_header_toggle: false
        entities:
          - switch.engine_heater
          - input_boolean.engine_heater
          - input_datetime.engine_heater
          - input_number.engine_heater
          - input_select.engine_heater
      - type: 'custom:useful-markdown-card'
        content: >
          ### Monday

          [[ food_planning.monday.state ]]

          ### Tuesday

          [[ food_planning.tuesday.state ]]

          ### Wednesday

          [[ food_planning.wednesday.state ]]

          ### Thursday

          [[ food_planning.thursday.state ]]

          ### Friday

          [[ food_planning.friday.state ]]

          ### Saturday

          [[ food_planning.saturday.state ]]

          ### Sunday

          [[ food_planning.sunday.state ]]

      - type: 'custom:useful-markdown-card'
        content: >
          [![Emby](/local/icons/emby.png "Emby")](http://homer.lan:8096/web/index.html)
          [![CouchPotato](/local/icons/couchpotato.png "CouchPotato")](http://homer.lan:5050)
          [![Sonarr](/local/icons/sonarr.png "Sonarr")](http://homer.lan:8989/)
          [![Sonarr](/local/icons/transmission.png "Transmission")](http://homer.lan:9091)
  
  - title: Sensors
    icon: mdi:thermometer
    background: center / cover no-repeat url("/local/background.jpg") fixed
    cards:
      - type: "custom:mini-graph-card"
        entities:
          - sensor.living_room
        height: 100
        line_width: 4
        font_size: 75
        color: '#3498db'
        hours_to_show: 48
        labels: true
      - type: horizontal-stack
        cards:
        - type: "custom:mini-graph-card"
          entities:
            - sensor.storage
          height: 100
          line_width: 4
          font_size: 75
          color: '#8898db'
          hours_to_show: 24
          labels: true
        - type: "custom:mini-graph-card"
          entities:
            - sensor.outside
          height: 100
          line_width: 4
          font_size: 75
          color: '#349800'
          hours_to_show: 24
          labels: true
      - type: horizontal-stack
        cards:
        - type: "custom:mini-graph-card"
          entities:
            - sensor.garage_temperature
          name: Garage
          height: 100
          line_width: 4
          font_size: 75
          color: '#8898db'
          hours_to_show: 24
          labels: true
        - type: "custom:mini-graph-card"
          entities:
            - sensor.bedroom
          height: 100
          line_width: 4
          font_size: 75
          color: '#349800'
          hours_to_show: 24
          labels: true
      - type: "custom:mini-graph-card"
        entities:
          - sensor.energy_daily
        height: 100
        line_width: 4
        font_size: 75
        color: '#3498db'
        hours_to_show: 6
        labels: true
      - type: vertical-stack
        cards:
        - type: glance
          title: Pierre
          entities:
            - entity: device_tracker.pierres_iphone
              name: State
            - entity: sensor.pierres_iphone_battery_level
              name: Battery
            - entity: sensor.pierres_iphone_battery_state
              name: Charging
        - type: map
          default_zoom: 8
          aspect_ratio: 50%
          entities:
            - device_tracker.pierres_iphone
      - type: vertical-stack
        cards:
        - type: glance
          title: Tove
          entities:
            - entity: device_tracker.toves_iphone
              name: State
            - entity: sensor.toves_iphone_battery_level
              name: Battery
            - entity: sensor.toves_iphone_battery_state
              name: Charging
        - type: map
          default_zoom: 8
          aspect_ratio: 50%
          entities:
            - device_tracker.toves_iphone

  - title: Floorplan
    icon: mdi:floor-plan
    background: center / cover no-repeat url("/local/background.jpg") fixed
    cards:
      - type: picture-glance
        image: /local/rooms/entrance.jpg
        title: Entrance
        entities:
          - entity: switch.entrance_mirror_switch
            icon: mdi:flower
          - entity: switch.entrance_unused_switch
            icon: mdi:help
      - type: picture-glance
        image: /local/rooms/livingroom.jpg
        title: Living Room
        entities:
          - entity: switch.living_room_balls_switch
            icon: mdi:balloon
          - entity: switch.living_room_window
            icon: mdi:window-maximize
          - entity: switch.living_room_stars_switch
            icon: mdi:door
          - entity: switch.christmas_tree
            icon: mdi:pine-tree
          - cover.projector_screen
      - type: picture-glance
        image: /local/rooms/diningroom.jpg
        title: Dining Room
        entities:
          - entity: switch.dining_room_locker_switch
            icon: mdi:locker
          - entity: switch.dining_room_vase_switch
          - entity: switch.dining_room_window
            icon: mdi:window-maximize
      - type: picture-glance
        image: /local/rooms/kitchen.jpg
        title: Kitchen
        entities:
          - entity: switch.kitchen_window
            icon: mdi:window-maximize
      - type: picture-glance
        image: /local/rooms/officejpg
        title: Office
        entities:
          - entity: switch.office_window
            icon: mdi:window-maximize
          - entity: switch.office_christmas_tree
            icon: mdi:pine-tree
      - type: picture-glance
        image: /local/rooms/upstairs.jpg
        title: Upstairs
        entities:
          - entity: switch.pierre_bedroom
            icon: mdi:lamp
          - entity: switch.bedroom_window
            icon: mdi:bed-empty
          - entity: switch.tims_room
            icon: mdi:baby
          - entity: switch.guest_room
            icon: mdi:hotel
      - type: picture-glance
        image: /local/rooms/basement.jpg
        title: Basement
        entities:
          - entity: switch.outside
            icon: mdi:tree
          - entity: switch.engine_heater
            icon: mdi:car
          - cover.garage_door

  - title: Monitor
    icon: mdi:wrench
    background: center / cover no-repeat url("/local/background.jpg") fixed
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            title: CPU
            entity: sensor.processor_use
          - type: gauge
            title: Free RAM
            max: 1024
            entity: sensor.memory_free
          - type: gauge
            title: Disk
            entity: sensor.disk_use_percent
      - type: glance
        entities:
          - entity: sensor.ip_address
          - entity: sensor.home_assistant_log
            name: Log
          - entity: sensor.home_assistant_v2_db
            name: DB
          - entity: sensor.process_mosquitto
            name: Mosquitto
      - type: glance
        columns: 3
        show_state: false
        entities:
          - entity: group.all_automations
            name: Automations
          - entity: group.all_devices
            name: Devices
          - entity: group.all_scripts
            name: Scripts
      - type: glance
        title: Speedtest
        entities:
          - entity: sensor.speedtest_ping
            name: Latency
          - entity: sensor.speedtest_download
            name: Down
          - entity: sensor.speedtest_upload
            name: Up
      - type: glance
        title: Transmission
        entities:
          - entity: sensor.transmission_status
            name: Status
          - entity: sensor.transmission_down_speed
            name: Down
          - entity: sensor.transmission_up_speed
            name: Up
      - type: glance
        columns: 4
        entities:
          - device_tracker.broadlink
          - device_tracker.garage_sensor
          - device_tracker.ap
          - device_tracker.apple_tv
          - device_tracker.printer
          - device_tracker.receiver
          - device_tracker.rpi_old
          - device_tracker.sonos
          - device_tracker.server
          - device_tracker.switch_kontor
          - device_tracker.switch_utsikt
          - device_tracker.switch_vardagsrum
          - device_tracker.kitchen_motion
          - device_tracker.bedroom_motion
      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker