automation:
  - alias: Turn on lights at sunset
    trigger:
      platform: sun
      event: sunset
      offset: '00:20:00'
    action:
      - service: switch.turn_on
        entity_id: group.downstair_lights

  - alias: Turn off lights in the morning
    trigger:
      platform: sun
      event: sunrise
      offset: '02:00:00'
    action:
      - service: switch.turn_ff
        entity_id: group.downstair_lights
