homeassistant:
  customize:
    group.remote_control:
      order: 1
    group.food_planning_group:
      order: 2
    group.tv_shows:
      order: 3
    group.movies:
      order: 4
    group.links:
      order: 5

group:

  outdoor:
    name: Today
    entities:
      - sun.sun
      - sensor.date__time
      - sensor.yr_humidity
      - sensor.yr_symbol
      - sensor.yr_temperature
      - sensor.yr_wind_speed

  links:
    name: Links
    entities:
      - !secret weblink1_sensor
      - !secret weblink2_sensor
      - !secret weblink3_sensor
      - !secret weblink4_sensor
