group:

  outdoor:
    name: Today
    entities:
      - sun.sun
      - sensor.date__time
      - sensor.yr_humidity
      - sensor.yr_symbol
      - sensor.yr_temperature
      - sensor.yr_wind_speed
      - sensor.ute_temperature

  movies:
    name: Movies
    entities:
      - sensor.movies_4
      - sensor.movies_3
      - sensor.movies_2
      - sensor.movies_1
      - sensor.movies_0

  tv_shows:
    name: TV Shows
    entities:
      - !secret media_watcher_tv1_sensor
      - !secret media_watcher_tv2_sensor
      - !secret media_watcher_tv3_sensor
      - !secret media_watcher_tv4_sensor
      - !secret media_watcher_tv5_sensor
      - !secret media_watcher_tv6_sensor
      - !secret media_watcher_tv7_sensor
      - !secret media_watcher_tv8_sensor

  links:
    name: Links
    entities:
      - !secret weblink1_sensor
      - !secret weblink2_sensor
      - !secret weblink3_sensor
      - !secret weblink4_sensor
