homeassistant:

  customize:
    cover.garageporten:
      homebridge_cover_type: garage_door

group:

  downstair_lights:
    name: All lights downstairs
    entities:
      - switch.telldus_tzwp100_plugin_switch_switch_3_0
      - switch.telldus_tzwp100_plugin_switch_switch_5_0
      - switch.telldus_tzwp100_plugin_switch_switch_2_0
      - switch.telldus_tzwp100_plugin_switch_switch_4_0
      - switch.telldus_tzwp100_plugin_switch_switch_6_0
      - switch.telldus_tzwp100_plugin_switch_switch_7_0

  entrance:
    name: Entrance
    entities:
      - switch.telldus_tzwp100_plugin_switch_switch_3_0
      - switch.telldus_tzwp100_plugin_switch_switch_5_0

  living_room:
    name: Living room
    entities:
      - sensor.vardagsrum_temperature
      - media_player.receiver
      - switch.telldus_tzwp100_plugin_switch_switch_2_0
      - switch.telldus_tzwp100_plugin_switch_switch_4_0

  kitchen:
    name: Kitchen
    entities:
      - binary_sensor.kitchen_sensor

  basement:
    name: Basement
    entities:
      - sensor.pannrum_temperature

  garage:
    name: Garage
    entities:
      - sensor.garage_temperature
      - sensor.garage_humidity
      - cover.garageporten

  dining_room:
    name: Dining room
    entities:
      - switch.telldus_tzwp100_plugin_switch_switch_6_0
      - switch.telldus_tzwp100_plugin_switch_switch_7_0

  office:
    name: Office
    entities:
      - switch.fonstret_i_arbetsrummet
