homeassistant:

  customize:
    cover.garageporten:
      homebridge_cover_type: garage_door
    switch.living_room_balls_switch:
      friendly_name: Living room balls
    switch.entrance_mirror_switch:
      friendly_name: Mirror
    switch.living_room_stars_switch:
      friendly_name: Living room stars
    switch.entrance_unused_switch:
      friendly_name: Entrance
    switch.dining_room_locker_switch:
      friendly_name: Dining room locker
    switch.dining_room_vase_switch:
      friendly_name: Dining room vase

group:

  downstair_lights:
    name: All lights downstairs
    entities:
      - switch.entrance_mirror_switch
      - switch.entrance_unused_switch
      - switch.living_room_balls_switch
      - switch.living_room_stars_switch
      - switch.dining_room_locker_switch
      - switch.dining_room_vase_switch

  entrance:
    name: Entrance
    entities:
      - switch.entrance_mirror_switch
      - switch.entrance_unused_switch

  living_room:
    name: Living room
    entities:
      - sensor.vardagsrum_temperature
      - media_player.receiver
      - switch.living_room_balls_switch
      - switch.living_room_stars_switch

  kitchen:
    name: Kitchen
    entities:
      - binary_sensor.kitchen_sensor

  basement:
    name: Basement
    entities:
      - sensor.pannrum_temperature

  garage:
    name: Garage
    entities:
      - sensor.garage_temperature
      - sensor.garage_humidity
      - cover.garageporten

  dining_room:
    name: Dining room
    entities:
      - switch.dining_room_locker_switch
      - switch.dining_room_vase_switch

  office:
    name: Office
    entities:
      - switch.fonstret_i_arbetsrummet
