homeassistant:

  customize:

    device_tracker.ap:
      icon: mdi:access-point-network
    device_tracker.apple_tv:
      icon: mdi:airplay
    device_tracker.printer:
      icon: mdi:printer
    device_tracker.receiver:
      icon: mdi:music-box
    device_tracker.rpi_old:
      icon: mdi:raspberrypi
    device_tracker.server:
      icon: mdi:server-network
    device_tracker.switch_kontor:
      icon: mdi:switch
    device_tracker.switch_utsikt:
      icon: mdi:switch
    device_tracker.switch_vardagsrum:
      icon: mdi:switch
    device_tracker.kitchen_motion:
      icon: mdi:run
    device_tracker.bedroom_motion:
      icon: mdi:run

group:

  server:
    name: Server
    entities:
      - sensor.myip
      - sensor.processor_use
      - sensor.memory_free
      - sensor.disk_use_percent_
      - sensor.log_size

  network:
    name: Network
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - script.perform_speedtest
      - sensor.transmission_status
      - sensor.transmission_down_speed
      - sensor.transmission_up_speed

  processes:
    name: Processes
    entities:
      - sensor.process_mosquitto

  hardware:
    name: Hardware
    entities:
      - device_tracker.broadlink
      - device_tracker.garage_sensor
      - device_tracker.ap
      - device_tracker.apple_tv
      - device_tracker.printer
      - device_tracker.receiver
      - device_tracker.rpi_old
      - device_tracker.sonos
      - device_tracker.server
      - device_tracker.switch_kontor
      - device_tracker.switch_utsikt
      - device_tracker.switch_vardagsrum
      - device_tracker.kitchen_motion
      - device_tracker.bedroom_motion
