homeassistant:

  customize:

    sensor.homekit_code:
      icon: mdi:home

group:

  people_devices:
    name: People and Devices
    entities:
      - device_tracker.pierres_iphone
      - sensor.pierres_iphone_battery_level_3
      - sensor.pierres_iphone_battery_state_3
      - device_tracker.toves_iphone
      - device_tracker.tove_ipad
      - device_tracker.tove_macbook
      - device_tracker.pierre_macbook
      - device_tracker.pierre_work_phone
      - sensor.homekit_code

  system_messages:
    name: System related messages
    entities:
      - device_tracker.pierre_iphone

  family:
    name: All people in family
    entities:
      - device_tracker.pierres_iphone
      - device_tracker.toves_iphone

  pierre_travel:
    name: Pierre Travel Times
    entities:
      - sensor.pierre_to_work
      - sensor.pierre_to_home
