homeassistant:

  customize:
    input_text.stream_url:
      friendly_name: URL
    script.start_stream:
      friendly_name: Play

group:
  airplay:
    name: AirPlay
    entities:
      - input_text.stream_url
      - input_select.stream_player
      - script.start_stream

input_select:
  stream_player:
    name: Media Player
    options:
      - media_player.apple_tv
      - media_player.sonos

input_text:
  stream_url:
    name: Stream URL
    initial: ''

script:
  start_stream:
    alias: Play Stream
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: '{{ states("input_select.stream_player") }}'
          media_content_type: VIDEO
          media_content_id: '{{ states("input_text.airplay_url") }}'
