food_planning:
  file_id: !secret food_planning_document
  days:
    - name: Monday
      day_name: Mån
      day_number: 0
    - name: Tuesday
      day_name: Tis
      day_number: 1
    - name: Wednesday
      day_name: Ons
      day_number: 2
    - name: Thursday
      day_name: Tors
      day_number: 3
    - name: Friday
      day_name: Fre
      day_number: 4
    - name: Saturday
      day_name: Lör
      day_number: 5
    - name: Sunday
      day_name: Sön
      day_number: 6

sensor:
  - platform: template
    sensors:
      food_today:
        friendly_name: Food today
        entity_id: sensor.time
        value_template: |-
          {% set food = ['food_planning.monday', 'food_planning.tuesday',
                         'food_planning.wednesday', 'food_planning.thursday',
                         'food_planning.friday', 'food_planning.saturday',
                         'food_planning.sunday'] %}
          {{ states(food[now().weekday()]) }}
