automation:
  - alias: Startup notification
    trigger:
      platform: homeassistant
      event: start
    action:
      service: notify.system
      data_template:
        message: 'Home Assistant has started (IP: {{ states.sensor.myipopendnscom.state }})'
        title: System Notification

  - alias: Notify for new devices
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: notify.system
        data_template:
          message: >
            New device:
            {{trigger.event.data.host_name}}
            {{trigger.event.data.entity_id}}
          title: System Notification

  # - platform: command_line
  #   name: HomeKit code
  #   command: "grep pin /var/homebridge/config.json | cut -f 4 -d '\"'"

  # - alias: Warn if log file exceeds size
  #   trigger:
  #     platform: state
  #     entity_id: sensor.log_size
  #   condition:
  #     - condition: numeric_state
  #       entity_id: sensor.log_size
  #       above: 10 # KB
  #   action:
  #     - service: notify.system
  #       data:
  #         message: Log file is getting rather big
  #         title: System Message

sensor:
  - platform: command_line
    name: Log size
    command: "ls -s /home/homeassistant/.homeassistant/home-assistant.log | cut -f 1 -d ' '"
