automation:
  - alias: Startup notification
    trigger:
      platform: homeassistant
      event: start
    action:
      service: notify.system
      data_template:
        message: 'Home Assistant has started (IP: {{ states.sensor.myip.state }})'
        title: System Notification

  - alias: Notify for new devices
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: notify.system
        data_template:
          message: >
            New device:
            {{trigger.event.data.host_name}}
            {{trigger.event.data.entity_id}}
          title: System Notification

sensor:
  - platform: command_line
    name: Log size
    command: "ls -s /home/homeassistant/.homeassistant/home-assistant.log | cut -f 1 -d ' '"
