automation:
  - alias: Sonos off when nobody is home
    trigger:
      platform: state
      entity_id: group.family
      to: not_home
      for:
        hours: 0
        minutes: 5
        seconds: 0
    action:
     - service: switch.turn_off
       entity_id: switch.sonos_player

  - alias: Sonos off when Tim eats
    trigger:
      platform: time
      at: '18:30:00'
    action:
     - service: switch.turn_off
       entity_id: switch.sonos_player

homeassistant:
  customize:
    script.sonos_say:
      emulated_hue_hidden: true
    media_player.kok:
      emulated_hue_name: Sonos
    switch.sonos_player:
      emulated_hue_hidden: true

switch:
  - platform: template
    switches:
      sonos_player:
        friendly_name: Sonos
        entity_id: media_player.kok
        value_template: "{{ is_state('media_player.kok', 'playing') }}"
        turn_on:
          service: media_player.media_play
          entity_id: media_player.kok
        turn_off:
          service: media_player.media_pause
          entity_id: media_player.kok

script:
  radio:
    alias: Radio
    sequence:
      - service: media_player.volume_set
        entity_id: media_player.kok
        data:
          volume_level: 0.20
      - service: media_player.select_source
        entity_id: media_player.kok
        data:
          source: 'P3 99.3 (Populärmusik)'

  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: media_player.sonos_snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.sonos_unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: tts.google_say
       data_template:
         entity_id: "{{ sonos_entity }}"
         message: "{{ message }}"
         language: "sv"
     - delay: "{{ delay }}"
     - service: media_player.sonos_restore
       data_template:
         entity_id: "{{ sonos_entity }}"
