homeassistant:
  customize:
    script.sonos_say:
      emulated_hue: false
    media_player.kok:
      emulated_hue_name: Sonos

switch:
  - platform: template
    switches:
      sonos_player:
        friendly_name: Sonos
        value_template: "{{ is_state('media_player.kok', 'playing') }}"
        turn_on:
          service: media_player.media_play
          entity_id: media_player.kok
        turn_off:
          service: media_player.media_pause
          entity_id: media_player.kok

media_player:
  - platform: sonos

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: media_player.sonos_snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.sonos_unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: tts.google_say
       data_template:
         entity_id: "{{ sonos_entity }}"
         message: "{{ message }}"
         language: "sv"
     - delay: "{{ delay }}"
     - service: media_player.sonos_restore
       data_template:
         entity_id: "{{ sonos_entity }}"
