homeassistant:

  customize:
    sensor.speedtest_download:
      icon: mdi:download
    sensor.speedtest_upload:
      icon: mdi:upload
    sensor.speedtest_ping:
      icon: mdi:timer

    sensor.energy_daily:
      friendly_name: Today
    sensor.energy_monthly:
      friendly_name: Monthly

sensor:
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: process
      arg: mosquitto
  - platform: time_date
  - platform: dnsip
    name: IP-Address
  - platform: filesize
    file_paths:
      - /home/homeassistant/.homeassistant/home-assistant.log
      - /home/homeassistant/.homeassistant/home-assistant_v2.db

speedtestdotnet:
  scan_interval:
    hours: 4
  monitored_conditions:
    - ping
    - download
    - upload

folder_watcher:
  - folder: /home/homeassistant/.homeassistant/themes
    patterns:
      - '*.yaml'

automation:
  alias: Reload themes
  trigger:
    platform: event
    event_type: folder_watcher
  action:
    service: frontend.reload_themes

binary_sensor:
  - platform: command_line
    name: Car
    device_class: presence
    command: 'sudo /sbin/iwlist wlan0 scan 2> /dev/null | grep WiFi_OBDII | wc -l'
    payload_on: 1
    payload_off: 0
