automation:
  - alias: Process down
    trigger:
      platform: state
      entity_id:
        - sensor.process_mosquitto
    action:
      service: notify.system
      data_template:
        message: >
          {{ trigger.entity_id.split('.')[1] }} is {{ trigger.to_state.state.lower() }}
        title: System Notification

sensor:
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: process
      arg: mosquitto
  - platform: time_date
  - platform: dnsip
    name: IP-Address
