homeassistant:

  customize:
    sensor.speedtest_download:
      icon: mdi:download
    sensor.speedtest_upload:
      icon: mdi:upload
    sensor.speedtest_ping:
      icon: mdi:timer

sensor:
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: process
      arg: mosquitto
  - platform: time_date
  - platform: dnsip
    name: IP-Address
  - platform: filesize
    file_paths:
      - /home/homeassistant/.homeassistant/home-assistant.log
      - /home/homeassistant/.homeassistant/home-assistant_v2.db
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - ping
      - download
      - upload
