homeassistant:
  customize:
    sensor.pannrum_temperature:
      friendly_name: Basement
    sensor.sovrum_temperature:
      friendly_name: Bedroom
    sensor.ute_temperature:
      friendly_name: Outside
    sensor.vardagsrum_temperature:
      friendly_name: Living Room

tellduslive:
  host: !secret telldus_host
