sensor:
  - platform: google_travel_time
    api_key: !secret google_travel_key
    name: Pierre to home
    origin: device_tracker.pierres_iphone
    destination: zone.home
  - platform: google_travel_time
    api_key: !secret google_travel_key
    name: Pierre to work
    origin: device_tracker.pierres_iphone
    destination: zone.pierre_workplace