switch:
  - platform: template
    switches:
      downstair_lights:
        friendly_name: Downstair Lights
        value_template: "{{ is_state('group.downstair_lights', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: group.downstair_lights
        turn_off:
          service: switch.turn_off
          entity_id: group.downstair_lights

homeassistant:
  customize:
    switch.telldus_tzwp100_plugin_switch_switch_2_0:
      friendly_name: Living room balls
    switch.telldus_tzwp100_plugin_switch_switch_3_0:
      friendly_name: Mirror
    switch.telldus_tzwp100_plugin_switch_switch_4_0:
      friendly_name: Living room stars
    switch.telldus_tzwp100_plugin_switch_switch_5_0:
      friendly_name: Entrance
    switch.telldus_tzwp100_plugin_switch_switch_6_0:
      friendly_name: Dining room locker
    switch.telldus_tzwp100_plugin_switch_switch_7_0:
      friendly_name: Dining room vase